services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VITE_API_URL=http://localhost:3001
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "3001:3001"
    environment:
      - DOCKER=true
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongo:27017/instatag
      - PORT=3001
      - CORS_ORIGIN=http://localhost:5173,http://localhost:5174
    depends_on:
      - mongo
    volumes:
      - ./backend:/app
      - /app/node_modules
    dns:
      - 8.8.8.8

  mongo:
    image: mongo:7.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=instatag

volumes:
  mongo_data: