
# Dockerfile.backend
FROM node:18

WORKDIR /app

# Kopiuj pliki package.json i package-lock.json
COPY backend/package*.json ./

RUN apt-get update && apt-get install -y chromium
# Instaluj zależności
RUN npm ci --omit=dev

# Kopiuj kod źródłowy
COPY backend/ ./

# Ustaw port
EXPOSE 3001

# Uruchom aplikację
CMD ["npm", "start"]